name: Build and Push Docker Image

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main

# Define the jobs to be run
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up QEMU for building and running multi-platform Docker images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using secrets for security
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the Docker image
      - name: Push latest tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/calcpal-dyscalculia-flask-app-cnn:latest
